### ISSUE TITLE
Suggestsions

### ISSUE THREAD

**Issue by ArieHein** [cderue/terraform-for-nis2-compliance#3]
1. Externalize the owner name to a variable.
Need to think about the 'getting_started' resource as you have the git clone command there with hardcoded url.

2. Maybe using the file function to allow customization of the content of the markdowns without having to run terraform code, as content of md files tends to change a lot more dynamically and often than tf code does.

**Comment by cderue** [comment]
Thank you for this suggestion. Best regards.
